/* controller  for showing reminder of profile completeness
 
@Created by: Trupti Dhoka
@Created Date: 26/06/2015

--------------------------------------------------------------------------------
| Modified By      | Modified Date       | Version        | Description         |
--------------------------------------------------------------------------------
|Trupti Dhoka         26/06/2015            Initial Draft    
--------------------------------------------------------------------------------

------------------------------------------------------------------------------------
*/



public class ProfileCompletenessReminderCSS2_0ctler{




}