@isTest
    private class testchangeOwner {    
        
        /*public static testMethod void testchangeOwnermethod() {
        
                Account a = [Select ID from Account where RecordType.Name = 'Booked Account' LIMIT 1];
                Service_Tax_Detail__c std = new Service_Tax_Detail__c(
                                                Account__c = a.id);
                insert std;
        }*/
    }